# This is a basic workflow to help you get started with Actions

name: Schema generation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "odd-chaining" branch
  push:
    branches: [ "odd-chaining" ]
  pull_request:
    branches: [ "odd-chaining" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Build with Ant      
        working-directory: .github/opt
        run: ant 
      - name: Check Git Status 
        run: git status  
      - name: Commit and Push
        uses: actions-x/commit@v6
        with:
          message: "schema update"
